// Copyright 2017-2021 @subgame/types authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@subgame/types', version: '0.0.1' };
